before_install: |
  curl http://dist.crystal-lang.org/apt/setup.sh | sudo bash
  sudo apt-get -q update
install:
  - sudo apt-get install crystal
  - crystal deps
  - git clone https://github.com/manastech/crystal.git
  - cd crystal
  - make
script:
  - bin/crystal deps
  - bin/crystal spec