language: c
before_install: |
  curl http://dist.crystal-lang.org/apt/setup.sh | sudo bash
  sudo apt-get -q update

install: |
  sudo apt-get install crystal
  crystal deps

script:
  - crystal deps
  - crystal spec
  - crystal examples/test.cr
  - crystal examples/view_test.cr
  - crystal examples/simple_application.cr
